clearAll;
scoresByPose = testLineFinding('real');
save('real_scores','scoresByPose');
scoresByPose = testLineFinding('baseline'); 
save('baseline_scores','scoresByPose');
scoresByPose = testLineFinding('sim'); 
save('sim_scores','scoresByPose');
scoresByPose = testLineFinding('sim_pooled'); 
save('sim_pooled_scores','scoresByPose');
scoresByPose = testLineFinding('sim_local_match'); 
save('sim_local_match_scores','scoresByPose');